name: Fetch Kaggle Datasets and Push to GitHub

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Kaggle CLI
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_API_KEY }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Fetch Kaggle Datasets
        run: |
          mkdir -p datasets
          cd datasets
          
          kaggle datasets download -d adorigueto/cnc-turning-roughness-forces-and-tool-wear --unzip -p cnc-turning-roughness-forces-and-tool-wear
          kaggle datasets download -d maximilianfellhuber/cnc-machining-data --unzip -p cnc-machining-data
          kaggle datasets download -d shasun/tool-wear-detection-in-cnc-mill --unzip -p tool-wear-detection-in-cnc-mill
          
          cd ..

      - name: Push to GitHub
        run: |
          git config --global user.name "krish17Nov"
          git config --global user.email "kr.17nov@gmail.com"
          git add datasets/
          git commit -m "Added CNC datasets from Kaggle"
          git push origin main
